### ISSUE TITLE
Exception When Removing Old Backups

### ISSUE THREAD

**Issue by LordNex** [Tyrsis/EssentialsPlugin#59]
2015-01-10 08:38:53.145 - Removed old backup: F:\SEDedicatedBackup\AutoBackup\Ba
ckup-1-12-2014-03-00\Backup-1-12-2014-03-00.zip
2015-01-10 08:38:53.146 - Removed old backup: F:\SEDedicatedBackup\AutoBackup\Ba
ckup-10-12-2014-03-00\Backup-10-12-2014-03-00.zip
2015-01-10 08:38:53.148 - Removed old backup: F:\SEDedicatedBackup\AutoBackup\Ba
ckup-10-12-2014-15-00\Backup-10-12-2014-15-00.zip
2015-01-10 08:38:53.153 - ProcessBackup.Handle(): System.IO.IOException: The dir
ectory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean
 recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recur
sive, Boolean checkHost)
   at EssentialsPlugin.ProcessHandler.ProcessBackup.CleanupBackups()
   at EssentialsPlugin.ProcessHandler.ProcessBackup.Handle()

**Comment by Tyrsis** [comment]
Temp error, should fix next time backup is run.  Might have had a locking issue.  Not really much to be concerned about.
