### ISSUE TITLE
Essential error on session load

### ISSUE THREAD

**Issue by Vl4dim1r** [Tyrsis/EssentialsPlugin#74]
i've seen this previously, and a disable/enable usually fixes it. However, re-enabling Essentials results in zero functionality of the plugin.

'''Finished loading WorldManager
Starting chat listener...
Chat listener is now sending messages to http://10.0.0.11/api/serelay/chat/postE
very 2000 millisecond
Finished initializing plugins
2015-01-29 14:14:43.526 - Handler Problems: 1000 - System.NullReferenceException
: Object reference not set to an instance of an object.
   at EssentialsPlugin.ProcessHandler.ProcessProtection.ProtectedEntity(IMyEntit
y entity, ProtectedItem item)
   at EssentialsPlugin.ProcessHandler.ProcessProtection.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass2.<PluginProcessing>b__0()
2015-01-29 14:14:44.653 - Handler Problems: 1000 - System.NullReferenceException
: Object reference not set to an instance of an object.
   at EssentialsPlugin.ProcessHandler.ProcessProtection.ProtectedEntity(IMyEntit
y entity, ProtectedItem item)
   at EssentialsPlugin.ProcessHandler.ProcessProtection.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass2.<PluginProcessing>b__0()
2015-01-29 14:14:45.780 - Handler Problems: 1000 - System.NullReferenceException
: Object reference not set to an instance of an object.
   at EssentialsPlugin.ProcessHandler.ProcessProtection.ProtectedEntity(IMyEntit
y entity, ProtectedItem item)
   at EssentialsPlugin.ProcessHandler.ProcessProtection.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass2.<PluginProcessing>b__0()
2015-01-29 14:14:46.914 - Handler Problems: 1000 - System.NullReferenceException
: Object reference not set to an instance of an object.
   at EssentialsPlugin.ProcessHandler.ProcessProtection.ProtectedEntity(IMyEntit
y entity, ProtectedItem item)
   at EssentialsPlugin.ProcessHandler.ProcessProtection.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass2.<PluginProcessing>b__0()
2015-01-29 14:14:48.034 - Handler Problems: 1000 - System.NullReferenceException
: Object reference not set to an instance of an object.
   at EssentialsPlugin.ProcessHandler.ProcessProtection.ProtectedEntity(IMyEntit
y entity, ProtectedItem item)
   at EssentialsPlugin.ProcessHandler.ProcessProtection.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass2.<PluginProcessing>b__0()
2015-01-29 14:14:49.152 - Handler Problems: 1000 - System.NullReferenceException
: Object reference not set to an instance of an object.
   at EssentialsPlugin.ProcessHandler.ProcessProtection.ProtectedEntity(IMyEntit
y entity, ProtectedItem item)
   at EssentialsPlugin.ProcessHandler.ProcessProtection.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass2.<PluginProcessing>b__0()
2015-01-29 14:14:50.274 - Handler Problems: 1000 - System.NullReferenceException
: Object reference not set to an instance of an object.
   at EssentialsPlugin.ProcessHandler.ProcessProtection.ProtectedEntity(IMyEntit
y entity, ProtectedItem item)
   at EssentialsPlugin.ProcessHandler.ProcessProtection.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass2.<PluginProcessing>b__0()
2015-01-29 14:14:52.372 - Unloading plugin 'f767bda5-0a8c-4813-85fd-a5a2341778e8
'
2015-01-29 14:14:52.377 - Shutting down plugin: Dedicated Server Essentials - 1.
0.2.1652
Loading plugins ...
Scanning: C:\ProgramData\SpaceEngineersDedicated\Resource-Acquisition-Division\M
ods
Finished loading plugins
Loading plugins ...
Scanning: C:\ProgramData\SpaceEngineersDedicated\Resource-Acquisition-Division\M
ods
Finished loading plugins
2015-01-29 14:14:53.948 - Initializing plugin at C:\ProgramData\SpaceEngineersDe
dicated\Resource-Acquisition-Division\Mods\Essentials\Essentials.dll - f767bda5-
0a8c-4813-85fd-a5a2341778e8'
2015-01-29 14:14:55.453 - Stopping all ships
2015-01-29 14:14:55.476 - 0 ships have been stopped
2015-01-29 14:14:55.496 - Plugin 'Dedicated Server Essentials' initialized. (Ver
sion: 1.0.2.1652  ID: f767bda5-0a8c-4813-85fd-a5a2341778e8)
'''

**Comment by Tyrsis** [comment]
Turn off ProtectedEnabled, as that feature does not work right now.

**Comment by Vl4dim1r** [comment]
I had an issue with /admin scan as well. Is that part of it?

**Comment by Tyrsis** [comment]
No it's different.  What is the issue with scan?  There are a lot of different scans.

**Comment by Vl4dim1r** [comment]
I am trying the '/admin scan grid', any of the types, but particularly by
owner or name. We tried after the SE update, before the SESE update and
were gettin object not set to reference errors, now nothing in Essentials
seems to work. We disable ProtectedEnabled and restarted the server to be
safe, and still nothing. '/admin scan grid nobeacon/nopower worked earlier,
but not anymore, even basic '/admin' and '/info' dont work.

Do you mind if I add you on Steam? I own the community that General Wrex
was developing for, before he left all of us for WoW, and it woulf be nice
to have direct contact with the lead SESE dev, so we know what errors to
expect. My steamname is "[XTT] Vl4dim1r", community website:
http://ettech.net. I'm replying via mobile email, so I apologize for the
lack of proper formatting.

**Comment by dodexahedron** [comment]
Please download this release: https://github.com/dodexahedron/EssentialsPlugin/releases/tag/v1.0.2.1669-alpha

The release currently available here is only compatible with versions of SESE before 0.3.0.
That will be fixed soon, but until then you can download from my fork.

**Comment by Tyrsis** [comment]
I've pretty much stopped supporting the nobeacon scan, as it's very old.  It's better to use /admin scan grids excludesblocksubtype:Beacon.  Try it and confirm it works, but I'm pretty sure it does.
