### ISSUE TITLE
Docking not working?

### ISSUE THREAD

**Issue by fngizzardbrain** [Tyrsis/EssentialsPlugin#87]
In the game i get "You are inside a valid docking zone: Landing"

But when i type the command "/dock dock Landing" nothing happens in game. However the console has this error

<code>
2015-02-21 14:23:46.846 - Thread: 23 -> COMMAND 144115188075855873 - 188243260419632401: /dock dock Landing
2015-02-21 14:23:46.865 - Thread: 23 -> ChatHandler Error: System.MissingFieldException: Field not found: 'Sandbox.Definitions.MyCubeBlockDefinition.Mass'.
   at EssentialsPlugin.Utility.Entity.CalculateMass(IMyEntity entity)
   at EssentialsPlugin.ChatHandlers.HandleDockDock.HandleCommand(UInt64 userId, String[] words)
   at EssentialsPlugin.Essentials.HandleChatMessage(UInt64 steamId, String message)
</code>

**Comment by theevilhobo** [comment]
Getting the same issue, along with alot of other features not working with this plugin!

**Comment by fngizzardbrain** [comment]
I'm guessing Essentials is abandoned? Has anyone found another mod that does something similar?

**Comment by theevilhobo** [comment]
Looks like it. Pitty

**Comment by Tyrsis** [comment]
It's not abandoned, I've just been busy unfortunately.  That's just how the world works.  I'll hopefully update soon.
