### ISSUE TITLE
Dynamic Turret Management Type not working correctly

### ISSUE THREAD

**Issue by Ragnar24** [Tyrsis/EssentialsPlugin#95]
First off thank you for the plugin. It has helped me admin the server tremendously.

Alright so, here is the current settings:
Just to be thorough I will list all dynamic settings

Conceal Distance: 10000
Conceal Enabled: True
Conceal Ignore SubType List: N/A
Conceal Include Large Grid: False
Conceal Include Med Bays: True
Show Messages: False

And here we go!

Turret Allow Exemption: False
Turret Management Type: Enemy
Turret Management Enabled: True
Turret Target Distance: 2000

Here is what I have done to troubleshoot:

Set Target Distance to 2 and shut off turrets by the /off turrets command.
The turrets stayed off.

After waiting 5 minutes I raised the target distance to 2000 meters again.
Immediately turned the turrets on.

The turrets turn on when anyone is around. Not only enemies.

Here is an error I keep getting in the SE CMD that relates to turrets:

2015-02-28 17:20:30.318 - CheckAndDisableTurrets(): System.InvalidOperationExcep
tion: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at 91D02AC963BE35D1F9C1B9FBCFE1722D.90EEEB83794016DCC5702A04E8A81212.6E272D36
1DDA95C56A51FC023CF78511(HashSet`1 617C65251A1E9638B0D6303BB7250F68, Func`2 A21F
1357B3120C7B56E81B0E31A9BD4C)
   at EssentialsPlugin.EntityManagers.TurretManagement.CheckAndEnableTurrets()

What can I do to have the turrets turn off while enemy is not around?

Thank you in advance,
Ragnar

**Comment by EngineerBean** [comment]
I also have a similar issue related to turret management. Players have been reporting that faction members cause the turrets to turn on, yet faction founder only online they stay off. The same 'CheckAndDisableTurrets' error also occurs many times. Changing ownership of turret to faction member does not make a difference.
