### ISSUE TITLE
Latest Patch Issues

### ISSUE THREAD

**Issue by Lordicon** [Tyrsis/EssentialsPlugin#98]
Seems the new patch i causing issues which is messing with the essentials. Entities are not displaying at all and getting errors with some of the plugin settings.

**Comment by devu** [comment]
I am getting Vrage.Utils.MyStringId method missing from Vrage.Library error. Esentials runs and perform most of the tasks but in-game chat commands are broken. Duplicated entities etc. Never had this problem before.

**Comment by Lordicon** [comment]
This is what I am getting on load..

2015-03-27 13:57:12.806 - Handler Problems: 400 - System.TypeLoadException: Coul
d not load type 'VRage.Utils.MyStringId' from assembly 'VRage.Library, Version=1
.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at SEModAPIInternal.API.Entity.BaseObject..ctor(MyObjectBuilder_Base baseEnti
ty)
   at SEModAPIInternal.API.Entity.BaseEntity..ctor(MyObjectBuilder_EntityBase ba
seEntity) in d:\BC\SpaceEngineers\SE-Community-Mod-API\SEModAPIInternal\API\Enti
ty\BaseEntity.cs:line 71
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGridEntity..ctor(FileI
nfo prefabFile) in d:\BC\SpaceEngineers\SE-Community-Mod-API\SEModAPIInternal\AP
I\Entity\Sector\SectorObject\CubeGridEntity.cs:line 59
   at EssentialsPlugin.ProcessHandler.ProcessCommunication.AddGlobalRelay()
   at EssentialsPlugin.ProcessHandler.ProcessCommunication.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass2.<PluginProcessing>b__0()
